options(warn=-1)
library(OpenML)
library(ggplot2)
library(cowplot)
library(mlr)
library(graphics)
library(rpart)
library(party)
library(rattle)
library(mlbench)
library(caret)
library(clusterGeneration)
library(mnormt)
library(corrplot)
library(RWeka)
library(partykit)

iris = getOMLDataSet(did = 10, verbosity=0)$data
# iris<-iris[!(iris$class=="fibrosis" | iris$class=="normal"),]
iristask = makeClassifTask(data = iris, target ="class")
rpart = makeLearner("classif.rpart")
rpart = setHyperPars(rpart, cp = 0, minbucket=4)
model = train(rpart, iristask)
fancyRpartPlot(model$learner.model, sub="")
